### ISSUE TITLE
not working as intended?

### ISSUE THREAD

**Issue by eskoONE** [Kuuhhl/polybar-corona-widget#1]
the value that is getting pulled from https://api.covid19api.com/live/country/germany/status/confirmed is not the latest value. i dont know how to pull that latest value to fix the issue but ill look into it if you dont have the time to fix it. 

as it is right now, the script is not useful since its pulling the data from 

Date | "2021-01-14T00:00:00Z"

instead of current date.

**Comment by Kuuhhl** [comment]
Hi, thanks for reporting the issue!
I have messaged the API-maintainer to ask him if his API is still being updated. 
If it isn't, I'll have to look for another data-source.
I'll update you if when I know more.

**Comment by Kuuhhl** [comment]
I now realized I made a mistake myself when parsing the data. 
I assumed the endpoint I was using would return an array of all provinces in the country.
What it actually does is return the data for different timestamps. 
This means the first items in the list are the oldest records, while the higher numbers (like 2143) are the most up-to-date records.
I'll try to fix my script as soon as I can.

**Comment by Kuuhhl** [comment]
The issue should be fixed now with my latest commit: https://github.com/Kuuhhl/polybar-corona-widget/commit/967438bf814b745992d28e58131a6cd9bdc90fa8
